import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API='';
const modules = [
  ['dashboard','Dashboard'], ['quotes','Quotes'], ['jobs','Jobs'], ['schedules','Schedule'], ['staff','Staff'], ['assets','Assets'], ['crews','Crews'], ['materials','BOQ / Materials'], ['suppliers','Suppliers'], ['purchase-orders','Purchase Orders'], ['variations','Variations'], ['timesheets','Timesheets'], ['claims','Claims'], ['diaries','Site Diaries'], ['documents','Documents'], ['photos','Photos'], ['actions','Actions'], ['client-updates','Client Updates'], ['rfis','RFIs'], ['permits','Permits'], ['risks','Risks'], ['reports','Reports']
];
const moduleFields = {
  quotes:['quote_number','client','site','status','scope'], jobs:['job_number','client','site','status','current_phase','manager'], schedules:['site','task','day','status'], staff:['full_name','short_name','role','trade','status'], assets:['asset_code','display_name','asset_type','status','location'], crews:['name','type','members'], materials:['job_id','item','qty','unit','status'], suppliers:['name','contact','phone'], 'purchase-orders':['supplier','job_id','description','value','status'], variations:['job_id','description','value','status'], timesheets:['staff','job_id','day','hours','status'], claims:['job_id','description','value','status'], diaries:['job_id','day','summary','status'], documents:['job_id','title','type','status'], photos:['job_id','title','url','status'], actions:['owner','title','priority','status'], 'client-updates':['client','subject','status'], rfis:['job_id','question','status'], permits:['job_id','permit','status'], risks:['job_id','risk','severity','status'], reports:['title','type','status']
};
function money(n){return '$'+Number(n||0).toLocaleString();}
function quoteTotal(q){return (q.items||[]).reduce((s,i)=>s+Number(i.qty||0)*Number(i.rate||0),0);}
function siteShort(s=''){return s.replace(/ Intersection Upgrade| Signal Upgrade| Stage 1/gi,'').toUpperCase();}
async function api(path, opts){const r=await fetch('/api/'+path,{headers:{'Content-Type':'application/json'},...opts}); if(!r.ok) throw new Error(await r.text()); return r.json();}

function Login({onLogin}){const [email,setEmail]=useState('admin@amtek.local'); const [password,setPassword]=useState('admin123'); const [err,setErr]=useState('');
 async function submit(e){e.preventDefault(); setErr(''); try{const res=await api('auth/login',{method:'POST',body:JSON.stringify({email,password})}); localStorage.setItem('amtek_session',JSON.stringify(res)); onLogin(res.user);}catch{setErr('Invalid login. Use admin@amtek.local / admin123');}}
 return <div className="loginPage"><div className="loginBrand"><img src="/logo.png"/><h1>AMTEK Solutions</h1><p>Traffic operations, quoting, scheduling and delivery control.</p></div><form className="loginCard" onSubmit={submit}><h2>Sign in</h2><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button>Login</button><small>Demo: admin@amtek.local / admin123</small></form></div>
}

function Sidebar({active,setActive,onLogout}){return <aside className="side"><div className="logoBox"><img src="/logo.png"/><span>AMTEK</span></div><nav>{modules.map(([k,l])=><button key={k} onClick={()=>setActive(k)} className={active===k?'active':''}>{l}</button>)}</nav><button className="logout" onClick={onLogout}>Logout</button></aside>}

function App(){const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('amtek_session')||'null')?.user}catch{return null}}); const [active,setActive]=useState('dashboard'); if(!user) return <Login onLogin={setUser}/>; return <div className="app"><Sidebar active={active} setActive={setActive} onLogout={()=>{localStorage.removeItem('amtek_session');setUser(null)}}/><main><Header user={user}/>{active==='dashboard'?<Dashboard setActive={setActive}/>:active==='quotes'?<Quotes/>:<Module name={active}/>}</main></div>}
function Header({user}){return <header className="top"><div><h1>Operations Dashboard</h1><p>Welcome back, {user.name}</p></div><div className="pill">🌤️ 20°C &nbsp; | &nbsp; Live local mode</div></header>}

function Dashboard({setActive}){const [data,setData]=useState({}); const [ex,setEx]=useState([]); useEffect(()=>{api('dashboard/board').then(setData); api('dashboard/exceptions').then(setEx)},[]); const jobs=data.jobs||[]; const staff=data.staff||[]; const assets=data.assets||[]; const quotes=data.quotes||[]; const schedules=data.schedules||[]; const days=['Mon','Tue','Wed','Thu','Fri','Mon+','Tue+','Wed+','Thu+','Fri+'];
 const rows=(jobs.length?jobs:[]).slice(0,4);
 return <div className="dash">
  <section className="stats"><Stat label="Quotes" value={quotes.length} sub="active records"/><Stat label="Jobs" value={jobs.length} sub="in system"/><Stat label="Staff" value={staff.length} sub="registered"/><Stat label="Assets" value={assets.length} sub="registered"/><Stat label="Alerts" value={ex.length} sub="exceptions" danger/></section>
  <section className="gridDash"><div className="board"><div className="boardHead"><div><h2>Master Schedule - Fortnight View</h2><p>Visual operations board</p></div><button onClick={()=>setActive('schedules')}>+ New Activity</button></div><div className="boardGrid"><div className="siteHead">Site / Job</div>{days.map((d,i)=><div className={'dayHead '+(i===0?'today':'')} key={i}>{d}{i===0&&<small>Today</small>}</div>)}{rows.map((j,ix)=><React.Fragment key={j.id}><div className="siteCell"><b>{siteShort(j.site)}</b><span>{j.current_phase}</span><small>{j.id}</small></div>{days.map((d,i)=>{const card=schedules.find(s=>s.job_id===j.id&&(s.day===d||i===ix));return <div className="dayCell" key={i}>{card&&<WorkCard card={card}/>}</div>})}</React.Fragment>)}</div></div><aside className="alerts"><h3>Exceptions & Alerts</h3>{ex.length?ex.map((e,i)=><div className="alert" key={i}>⚠️ {e.message}</div>):<p className="muted">No live exceptions</p>}<h3>Assets Today</h3>{assets.slice(0,4).map(a=><div className="miniRow" key={a.id}><span>🚧 {a.asset_code||a.display_name}</span><small>{a.status}</small></div>)}</aside></section>
 </div>}
function Stat({label,value,sub,danger}){return <div className={'stat '+(danger?'danger':'')}><small>{label}</small><strong>{value}</strong><span>{sub}</span></div>}
function WorkCard({card}){return <div className="work"><b>{card.task}</b><div>{(card.assets||[]).map(a=><span className="asset" key={a}>🚧 {a}</span>)}</div><div>{(card.staff||[]).map(s=><span className="bubble" key={s}>{s}</span>)}</div><small>{card.status}</small></div>}

function Quotes(){const [quotes,setQuotes]=useState([]); const [editing,setEditing]=useState(null); useEffect(()=>{load()},[]); async function load(){setQuotes(await api('quotes'))} async function save(q){await api(q.id?'quotes/'+q.id:'quotes',{method:q.id?'PUT':'POST',body:JSON.stringify(q)}); setEditing(null); load()} async function del(id){if(confirm('Delete quote?')){await api('quotes/'+id,{method:'DELETE'}); load()}} async function convert(id){await api('quotes/'+id+'/convert-to-job',{method:'POST'}); alert('Quote converted to job'); load()} return <div className="page"><div className="pageHead"><h2>Quotes</h2><button onClick={()=>setEditing({quote_number:'',client:'',site:'',status:'Draft',scope:'',items:[{description:'',qty:1,rate:0}]})}>+ New Quote</button></div>{editing&&<QuoteForm quote={editing} onSave={save} onCancel={()=>setEditing(null)}/>}<div className="cards">{quotes.map(q=><div className="record" key={q.id}><h3>{q.quote_number||q.id}</h3><p>{q.client} - {q.site}</p><p>{q.scope}</p><b>{money(quoteTotal(q))}</b><span className="tag">{q.status}</span><div className="actions"><button onClick={()=>setEditing(q)}>Edit</button><button onClick={()=>convert(q.id)}>Convert to Job</button><button onClick={()=>location.href='/api/exports/quotes'}>Export</button><button className="dangerBtn" onClick={()=>del(q.id)}>Delete</button></div></div>)}</div></div>}
function QuoteForm({quote,onSave,onCancel}){const [q,setQ]=useState(JSON.parse(JSON.stringify(quote))); function item(i,k,v){const items=[...(q.items||[])]; items[i]={...items[i],[k]:v}; setQ({...q,items})} return <div className="form"><h3>{q.id?'Edit':'New'} Quote</h3><div className="formGrid"><input placeholder="Quote Number" value={q.quote_number||''} onChange={e=>setQ({...q,quote_number:e.target.value})}/><input placeholder="Client" value={q.client||''} onChange={e=>setQ({...q,client:e.target.value})}/><input placeholder="Site" value={q.site||''} onChange={e=>setQ({...q,site:e.target.value})}/><select value={q.status||'Draft'} onChange={e=>setQ({...q,status:e.target.value})}><option>Draft</option><option>Sent</option><option>Awarded</option><option>Rejected</option></select></div><textarea placeholder="Scope" value={q.scope||''} onChange={e=>setQ({...q,scope:e.target.value})}/><h4>Line Items</h4>{(q.items||[]).map((it,i)=><div className="line" key={i}><input placeholder="Description" value={it.description||''} onChange={e=>item(i,'description',e.target.value)}/><input type="number" value={it.qty||0} onChange={e=>item(i,'qty',e.target.value)}/><input type="number" value={it.rate||0} onChange={e=>item(i,'rate',e.target.value)}/><b>{money(Number(it.qty||0)*Number(it.rate||0))}</b></div>)}<button onClick={()=>setQ({...q,items:[...(q.items||[]),{description:'',qty:1,rate:0}]})}>+ Add Line</button><div className="total">Total: {money(quoteTotal(q))}</div><div className="actions"><button onClick={()=>onSave(q)}>Save Quote</button><button onClick={onCancel}>Cancel</button></div></div>}

function Module({name}){const [rows,setRows]=useState([]); const [edit,setEdit]=useState(null); const label=modules.find(m=>m[0]===name)?.[1]||name; const fields=moduleFields[name]||['title','description','status']; useEffect(()=>{load()},[name]); async function load(){setRows(await api(name))} async function save(r){await api(r.id?name+'/'+r.id:name,{method:r.id?'PUT':'POST',body:JSON.stringify(r)}); setEdit(null); load()} async function del(id){if(confirm('Delete record?')){await api(name+'/'+id,{method:'DELETE'}); load()}} return <div className="page"><div className="pageHead"><h2>{label}</h2><div><button onClick={()=>setEdit(Object.fromEntries(fields.map(f=>[f,''])))}>+ New</button><button onClick={()=>location.href='/api/exports/'+name}>Export CSV</button></div></div>{edit&&<GenericForm fields={fields} row={edit} onSave={save} onCancel={()=>setEdit(null)}/>}<table><thead><tr>{fields.map(f=><th key={f}>{f.replace(/_/g,' ')}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{fields.map(f=><td key={f}>{Array.isArray(r[f])?r[f].join(', '):String(r[f]??'')}</td>)}<td><button onClick={()=>setEdit(r)}>Edit</button><button onClick={()=>del(r.id)} className="dangerBtn">Delete</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No records yet. Use + New to create one.</div>}</div>}
function GenericForm({fields,row,onSave,onCancel}){const [r,setR]=useState({...row}); return <div className="form"><div className="formGrid">{fields.map(f=><input key={f} placeholder={f.replace(/_/g,' ')} value={Array.isArray(r[f])?r[f].join(', '):(r[f]??'')} onChange={e=>setR({...r,[f]:e.target.value})}/>)}</div><div className="actions"><button onClick={()=>onSave(r)}>Save</button><button onClick={onCancel}>Cancel</button></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
